import Head from 'next/head'
import next from 'next'
import styles from '../styles/About.module.css'
import Image from 'next/image'


export default function About() {
    return (
        <>
        <section>
        <Head>
                <title>Ammon Orgill Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </section>
        <div>
            <h1 className='flex justify-center text-[60px] md:text-[100px] mt-10 font-header'>Ammon Orgill</h1>
                <img 
                    src='/Ammon1.jpg'
                    alt='Ammon profile photo'
                    className='rounded-xl max-h-80 mx-auto'
                    // if you do this one you don't have to have the height and width (or fill) defined
                />
                <div>
                    <p className={styles.extraGreen}>
                        My name is Ammon Orgill and I'm a newly minted software engineer!
                        I love to build intuitive websties that people love to use. I have a passion for creating and building. 
                        I have years of corporate experience in Business Strategy & Operations which allowed me to develop in depth business acumen and a sharp eye for executing strategic initiaitves. I bring those skills to the table to ensure that products I create meet key business objectives. 

                        I am a passionate real estate investor, concert pianist, and competitive pickleball player. 
                    </p>

                </div>

                {/* load an image locally */}
                {/* <Image 
                    src='/Ammon1.jpg'
                    alt='Profile Photo'
                    width={356}
                    height={372}
                    // layout='fill'
                /> */}
                {/*  you can also use image tags */}


                {/* load an image hosted on another domain */}
                {/* <Image 
                    src='https://placekitten.com/400/500'
                    alt='portfolio cat'
                    width={400}
                    height={500}

                /> */}
        

        
        </div>

        <div className="p-4">
                <p className="text-2xl flex justify-center m-4 text-[50px] md:text-[100px] mt-32 mb-20 font-header underline">Skills</p>
                <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 gap-4 py-4">
                    <div className="mx-auto flex flex-col">
                        <img 
                            className="max-h-20 rounded-full shadow-lg"
                            src='/html.png'
                            alt='html'
                            />
                        <p className="mx-auto">HTML 5</p>
                    </div> 

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/css.png'
                            alt='css'
                            className="max-h-20 max-w-20 rounded-full shadow-lg "
                        />
                        <p className="mx-auto">CSS 3</p>
                    </div>  

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/js.png'
                            alt='javascript'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">javascript</p>
                    </div> 

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/node.png'
                            alt='node'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">Node.js</p>
                    </div>  

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/react.png'
                            alt='react'
                            className="max-h-20 rounded-full shadow-lg "
                        />
                        <p className="mx-auto">ReactJS</p>
                    </div>

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/python.png'
                            alt='python'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">Python</p>
                    </div>    

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/bootstrap.png'
                            alt='bootstrap'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">Bootstrap</p>
                    </div>  

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/tailwind.png'
                            alt='tailwind'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">Tailwind</p>
                    </div>  

                    
                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/mongo.png'
                            alt='mongo'
                            className="max-h-20 max-w-20 rounded-full shadow-lg"
                        />
                       <p className="mx-auto"> MongoDB</p>
                    </div>    

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/django.png'
                            alt='django'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                       <p className="mx-auto"> Django</p>
                    </div>    

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/express.png'
                            alt='express'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">Express</p>
                    </div>    

                    <div className="mx-auto flex flex-col">
                        <img 
                            src='/postgres.png'
                            alt='postgres'
                            className="max-h-20 rounded-full shadow-lg"
                        />
                        <p className="mx-auto">PostgreSQL</p>
                    </div>    
                </div>
            </div>
    </>

    )
}